# Generated by Django 4.2 on 2023-12-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_organistaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organistaion',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='organistaion',
            new_name='organisation',
        ),
    ]
